# Generated by Django 4.2.5 on 2023-12-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact_spamreport_user_delete_user_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, unique=True)),
                ('is_spam', models.BooleanField(default=False)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
