# Generated by Django 4.2.5 on 2023-12-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_phonenumber_reporter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpamReport',
        ),
    ]
