# Generated by Django 4.2.5 on 2023-12-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_spamreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='dummy_password', max_length=15, unique=True),
        ),
    ]
